#!/usr/bin/env bash

IMPORT_DIR="${IMPORT_DIR:-/mnt/vault/Media/beets-import}"

set -e
[ -n "$DEBUG" ] && set -x

while IFS= read -r -d '' RELEASE_FILE; do
    IMPORT_OPTS=(--search-id="$(cat "$RELEASE_FILE")")
    DISC_DIR="$(dirname "$RELEASE_FILE")"
    if [ -f "$DISC_DIR/comp" ]; then
        IMPORT_OPTS+=(--set=comp=1)
    fi
    beet import "${IMPORT_OPTS[@]}" "$DISC_DIR"
    rm -f "$DISC_DIR"/{release-id,comp}
    rmdir "$DISC_DIR"
done < <(find "$IMPORT_DIR" -name release-id -print0)
