#!/bin/bash

OUTPUT_DIR="$HOME/tmp/rip"

WHIPPER_ARGS="--prompt"
DISC_TEMPLATE="%A/%d/%A - %d"
TRACK_TEMPLATE="%A/%d/%t %n"


## Functions

ripped_disc_dir()
{
    # We've no easy way of knowing which folder we just ripped files to,
    # so we assume it's the most recently modified directory in the output
    # folder.
    find "$OUTPUT_DIR" -type d -print0 | \
        xargs -0 stat --format '%Y:%n' | \
        sort -nr | \
        cut -d : -f 2- | \
        head -n 1
}


read_tag()
{
    local tag="$1"
    local file="$2"
    metaflac --show-tag="$tag" "$file"
}


set_genre()
{
    local dir="$1"
    local genre
    if [ -z "$GENRES" ]; then
        read -r -p "Enter genres for disc (separated by semi-colons): " GENRES
    fi
    IFS=";"
    for genre in $GENRES; do
        metaflac --set-tag GENRE="$genre" "$dir"/*flac
    done
    unset IFS
}


## Main program

set -e

mkdir -p "$OUTPUT_DIR"

whipper cd rip \
    --output-directory "$OUTPUT_DIR" \
    --disc-template "$DISC_TEMPLATE" \
    --track-template "$TRACK_TEMPLATE" \
    "$WHIPPER_ARGS" \
    "$@"

cd "$OUTPUT_DIR"
set_genre "$(ripped_disc_dir)"
