#!/bin/bash

RIPPED="$HOME/tmp/rip"
ARCHIVED="$HOME/tmp/ripped-and-imported"

HOST="nas"
IMPORTS="/mnt/vault/Media/Music/import"


## Functions

artist()
{
    basename "$(dirname "$@")"
}


album()
{
    basename "$@"
}


make_release_id_file()
{
    local flac
    flac="$(find "$DISC" -name \*.flac | head -n 1)"
    echo -n "Getting MusicBrainz ID from '$(basename "$flac")' ... "
    metaflac --show-tag MUSICBRAINZ_ALBUMID "$flac" | sed 's,.*=,,' \
        > "$DISC"/release-id
    echo "ok"
}


remove_rip_cruft()
{
    # The cruft are files created by whipper that I don't need...
    rm -f "$DISC"/*.{cue,log,m3u,toc}
}


sync_album()
{
    rsync -av "$DISC" "$HOST:'$IMPORTS'/"
}


archive_local_copy()
{
    echo -n "Archiving $(album "$DISC") locally ... "
    mkdir -p "$ARCHIVED/$(artist "$DISC")"
    mv "$DISC" "$ARCHIVED/$(artist "$DISC")/"
    rmdir "$(dirname "$DISC")" 2>/dev/null || true
    echo "ok"
}


## Main program

set -e

IFS="
"

for DISC in $(find "$RIPPED" -mindepth 2 -maxdepth 2 -type d); do
    if [ "$(artist "$DISC")" = "Unknown Artist" ]; then
        echo "Skipping '$DISC'" 1>&2
        continue
    fi
    if [ "$(find "$DISC" -name \*.cue | wc -m)" -gt 0 ]; then
        echo "Skipping '$DISC' (ripping in progress)" 1>&2
        continue
    fi
    make_release_id_file
    remove_rip_cruft
    sync_album
    archive_local_copy
done
